package Kamen_Rider_Craft_4TH;


import java.util.Random;
import Kamen_Rider_Craft_4TH.util.Refercence;
import net.minecraft.entity.IMerchant;
import net.minecraft.entity.passive.EntityVillager.ITradeList;
import net.minecraft.entity.passive.EntityVillager.PriceInfo;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.Ingredient;
import net.minecraft.util.ResourceLocation;
import net.minecraft.village.MerchantRecipe;
import net.minecraft.village.MerchantRecipeList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.ForgeRegistries;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.common.registry.VillagerRegistry;
import net.minecraftforge.fml.common.registry.VillagerRegistry.VillagerCareer;
import net.minecraftforge.fml.common.registry.VillagerRegistry.VillagerProfession;
import net.minecraftforge.registries.IForgeRegistry;

public class CraftingRecipeForRider {
	public static void Crafrting(){
		
		//GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":energy"), new ResourceLocation(Refercence.MODID+":kamen_rider"),new ItemStack(RiderItems.energy,5), " a ","aba"," a ", 'a', new ItemStack(Items.DYE, 1, 4), 'b', Items.REDSTONE);		
		//GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":base_gun"), new ResourceLocation(Refercence.MODID+":kamen_rider"),new ItemStack(RiderItems.base_gun,1), "a  "," a "," ba", 'a', RiderItems.rider_circuit, 'b', Items.IRON_INGOT);	
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ryukihead"), new ResourceLocation("kr_ryuki"),new ItemStack(RiderItems.ryukihead,1), "aaa","a a", 'a', RiderItems.contract_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ryukitroso"), new ResourceLocation("kr_ryuki"),new ItemStack(RiderItems.ryukitroso,1), "a a","aaa","aaa", 'a', RiderItems.contract_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ryukilegs"), new ResourceLocation("kr_ryuki"),new ItemStack(RiderItems.ryukilegs,1), "aaa","a a","a a", 'a', RiderItems.contract_advent);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_ryuki"), new ResourceLocation("ryuki"),new ItemStack(RiderItems.v_buckle_ryuki,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.dragreder_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_knight"), new ResourceLocation("knight"),new ItemStack(RiderItems.v_buckle_knight,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.darkwing_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_scissors"), new ResourceLocation("scissors"),new ItemStack(RiderItems.v_buckle_scissors,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.volcancer_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_zolda"), new ResourceLocation("zolda"),new ItemStack(RiderItems.v_buckle_zolda,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.magnugiga_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_gai"), new ResourceLocation("gai"),new ItemStack(RiderItems.v_buckle_gai,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.metalgelas_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_raia"), new ResourceLocation("raia"),new ItemStack(RiderItems.v_buckle_raia,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.evildiver_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_ouja"), new ResourceLocation("ouja"),new ItemStack(RiderItems.v_buckle_ouja,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.venosnaker_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_tiger"), new ResourceLocation("tiger"),new ItemStack(RiderItems.v_buckle_tiger,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.destwilder_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_imperer"), new ResourceLocation("imperer"),new ItemStack(RiderItems.v_buckle_imperer,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.gigazelle_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_odin"), new ResourceLocation("odin"),new ItemStack(RiderItems.v_buckle_odin,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.goldphoenix_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_femme"), new ResourceLocation("femme"),new ItemStack(RiderItems.v_buckle_femme,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.blancwing_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_verde"), new ResourceLocation("verde"),new ItemStack(RiderItems.v_buckle_verde,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.biogreeza_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_ryuga"), new ResourceLocation("ryuga"),new ItemStack(RiderItems.v_buckle_ryuga,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.dragblacker_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":v_buckle_abyss"), new ResourceLocation("abyss"),new ItemStack(RiderItems.v_buckle_abyss,1), "aaa","aca","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.abysslasher_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":alternativebelt"), new ResourceLocation("alternative"),new ItemStack(RiderItems.alternativebelt,1), "aca","aaa","aaa", 'a', RiderItems.contract_advent, 'c', RiderItems.psycorogue_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":alternativezerobelt"), new ResourceLocation("alternative_0"),new ItemStack(RiderItems.alternativezerobelt,1), "aaa","aaa","aca", 'a', RiderItems.contract_advent, 'c', RiderItems.psycorogue_advent);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":drag_visor"), new ResourceLocation("ryuki"),new ItemStack(RiderItems.drag_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.dragreder_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":dark_visor"), new ResourceLocation("knight"),new ItemStack(RiderItems.dark_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.darkwing_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":scissors_visor"), new ResourceLocation("scissors"),new ItemStack(RiderItems.scissors_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.volcancer_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":magna_visor"), new ResourceLocation("zolda"),new ItemStack(RiderItems.magna_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.magnugiga_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":metal_visor"), new ResourceLocation("gai"),new ItemStack(RiderItems.metal_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.metalgelas_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":evil_visor"), new ResourceLocation("raia"),new ItemStack(RiderItems.evil_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.evildiver_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":veno_visor"), new ResourceLocation("ouja"),new ItemStack(RiderItems.veno_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.venosnaker_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":dest_visor"), new ResourceLocation("tiger"),new ItemStack(RiderItems.dest_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.destwilder_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gazelle_visor"), new ResourceLocation("imperer"),new ItemStack(RiderItems.gazelle_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.gigazelle_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gold_visor"), new ResourceLocation("odin"),new ItemStack(RiderItems.gold_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.goldphoenix_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":blanc_visor"), new ResourceLocation("femme"),new ItemStack(RiderItems.blanc_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.blancwing_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":bio_visor"), new ResourceLocation("verde"),new ItemStack(RiderItems.bio_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.biogreeza_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":dark_drag_visor"), new ResourceLocation("ryuga"),new ItemStack(RiderItems.dark_drag_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.dragblacker_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":abyss_visor"), new ResourceLocation("abyss"),new ItemStack(RiderItems.abyss_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.abysslasher_advent, 'c', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":slash_visor"), new ResourceLocation("alternative"),new ItemStack(RiderItems.slash_visor,1), "aca","aba","aaa", 'a', RiderItems.contract_advent, 'b', RiderItems.psycorogue_advent, 'c', miscellaneousRiderItems.base_sword);
		
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":faizhead"), new ResourceLocation("kr_faiz"),new ItemStack(RiderItems.faizhead,1), "aaa","a a", 'a', RiderItems.blank_mission_memory);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":faiztroso"), new ResourceLocation("kr_faiz"),new ItemStack(RiderItems.faiztroso,1), "a a","aaa","aaa", 'a', RiderItems.blank_mission_memory);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":faizlegs"), new ResourceLocation("kr_faiz"),new ItemStack(RiderItems.faizlegs,1), "aaa","a a","a a", 'a', RiderItems.blank_mission_memory);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":faizdriver"), new ResourceLocation("faiz"),new ItemStack(RiderItems.faizdriver,1), "aaa","aca","aaa", 'a', RiderItems.blank_mission_memory,  'c', RiderItems.faiz_mission_memory );
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kaixadriver"), new ResourceLocation("kaixa"),new ItemStack(RiderItems.kaixadriver,1), "aaa","aca","aaa", 'a', RiderItems.blank_mission_memory,  'c', RiderItems.kaixa_mission_memory );
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":deltadriver"), new ResourceLocation("delta"),new ItemStack(RiderItems.deltadriver,1), "aaa","aca","aaa", 'a', RiderItems.blank_mission_memory,  'c', RiderItems.delta_mission_memory );
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":psygadriver"), new ResourceLocation("psyga"),new ItemStack(RiderItems.psygadriver,1), "aaa","aca","aaa", 'a', RiderItems.blank_mission_memory,  'c', RiderItems.psyga_mission_memory );
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":orgadriver"), new ResourceLocation("orga"),new ItemStack(RiderItems.orgadriver,1), "aaa","aca","aaa", 'a', RiderItems.blank_mission_memory,  'c', RiderItems.orga_mission_memory );
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":faiz_edge"), new ResourceLocation("faiz"),new ItemStack(RiderItems.faiz_edge,1), "ama","aba","aaa", 'a', RiderItems.blank_mission_memory, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.faiz_mission_memory);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":axel_ray_gun"), new ResourceLocation("rio_trooper"),new ItemStack(RiderItems.axel_ray_gun,1), "aaa","aba","aaa", 'a', RiderItems.blank_mission_memory, 'b', miscellaneousRiderItems.base_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":faiz_blaster"), new ResourceLocation("faiz_blaster"),new ItemStack(RiderItems.faiz_blaster,1), "ama","aba","aaa", 'a', RiderItems.blank_mission_memory, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.faiz_blaster_mission_memory);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kaixa_blaygun"), new ResourceLocation("kaixa"),new ItemStack(RiderItems.kaixa_blaygun,1), "ama","aba","aaa", 'a', RiderItems.blank_mission_memory, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.kaixa_mission_memory);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":deltablaster"), new ResourceLocation("delta"),new ItemStack(RiderItems.deltablaster,1), "ama","aba","aaa", 'a', RiderItems.blank_mission_memory, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.delta_mission_memory);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":psyga_tonfa_edge"), new ResourceLocation("psyga"),new ItemStack(RiderItems.psyga_tonfa_edge,1), "ama","aba","aaa", 'a', RiderItems.blank_mission_memory, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.psyga_mission_memory);		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":orga_stlanzer"), new ResourceLocation("orga"),new ItemStack(RiderItems.orga_stlanzer,1), "ama","aba","aaa", 'a', RiderItems.blank_mission_memory, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.orga_mission_memory);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":bladehead"), new ResourceLocation("kr_blade"),new ItemStack(RiderItems.bladehead,1), "aaa","a a", 'a', RiderItems.bladecard);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":bladetroso"), new ResourceLocation("kr_blade"),new ItemStack(RiderItems.bladetroso,1), "a a","aaa","aaa", 'a', RiderItems.bladecard);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":bladelegs"), new ResourceLocation("kr_blade"),new ItemStack(RiderItems.bladelegs,1), "aaa","a a","a a", 'a', RiderItems.bladecard);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":bladedriver"), new ResourceLocation("blade"),new ItemStack(RiderItems.bladedriver,1), "aaa","aca","aaa", 'a', RiderItems.bladecard,  'c', RiderItems.changebeetle );
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":garrendriver"), new ResourceLocation("garren"),new ItemStack(RiderItems.garrendriver,1), "aaa","aca","aaa", 'a', RiderItems.bladecard,  'c', RiderItems.change_stag );
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":leangle_belt"), new ResourceLocation("leangle"),new ItemStack(RiderItems.leangle_belt,1), "aaa","aca","aaa", 'a', RiderItems.bladecard,  'c', RiderItems.change_spider );
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":chalicerouzer"), new ResourceLocation("chalice"),new ItemStack(RiderItems.chalicerouzer,1), "aaa","aca","aaa", 'a', RiderItems.bladecard,  'c', RiderItems.change_mantis );
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":glaive_buckle"), new ResourceLocation("glaive"),new ItemStack(RiderItems.glaive_buckle,1), "aaa","aca","aaa", 'a', RiderItems.bladecard,  'c', RiderItems.changekerberosglaive );
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":lance_buckle"), new ResourceLocation("lance"),new ItemStack(RiderItems.lance_buckle,1), "aaa","aca","aaa", 'a', RiderItems.bladecard,  'c', RiderItems.changekerberoslance );
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":larc_buckle"), new ResourceLocation("larc"),new ItemStack(RiderItems.larc_buckle,1), "aaa","aca","aaa", 'a', RiderItems.bladecard,  'c', RiderItems.changekerberoslarc );
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":rouze_absorber"), new ResourceLocation("blade"),new ItemStack(RiderItems.rouze_absorber,1), "aaa","aca","aaa", 'a', RiderItems.bladecard,  'c', RiderItems.fusion_eagle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":garren_absorber"), new ResourceLocation("garren"),new ItemStack(RiderItems.garren_absorber,1), "aaa","aca","aaa", 'a', RiderItems.bladecard,  'c', RiderItems.fusion_peacock);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":blayrouzer"), new ResourceLocation("blade"),new ItemStack(RiderItems.blayrouzer,1), "ama","aba","aaa", 'a', RiderItems.bladecard, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.changebeetle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":garrenrouzer"), new ResourceLocation("garren"),new ItemStack(RiderItems.garrenrouzer,1), "ama","aba","aaa", 'a', RiderItems.bladecard, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.change_stag);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":leanglerouzer"), new ResourceLocation("leangle"),new ItemStack(RiderItems.leanglerouzer,1), "ama","aba","aaa", 'a', RiderItems.bladecard, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.change_spider);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kingrouzer"), new ResourceLocation("blade_king"),new ItemStack(RiderItems.kingrouzer,1), "ama","aba","aaa", 'a', RiderItems.bladecard, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.evolution_caucasus);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":chalice_arrow"), new ResourceLocation("chalice"),new ItemStack(RiderItems.chalice_arrow,1), "ama","aba","aaa", 'a', RiderItems.bladecard, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.change_mantis);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":wild_slasher"), new ResourceLocation("wild_chalice"),new ItemStack(RiderItems.wild_slasher,1), "ama","aba","aaa", 'a', RiderItems.bladecard, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.evolution_paradoxa);

		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":wild_chalice_arrow"),new ResourceLocation("wild_chalice"),new ItemStack(RiderItems.wild_chalice_arrow), new Ingredient[]{Ingredient.fromItem(RiderItems.chalice_arrow),Ingredient.fromItem(RiderItems.wild_slasher)});	
	
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":hibikihead"), new ResourceLocation("kr_hibiki"),new ItemStack(RiderItems.hibikihead,1), "aaa","a a", 'a', RiderItems.oni_ore);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":hibikitroso"), new ResourceLocation("kr_hibiki"),new ItemStack(RiderItems.hibikitroso,1), "a a","aaa","aaa", 'a', RiderItems.oni_ore);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":hibikilegs"), new ResourceLocation("kr_hibiki"),new ItemStack(RiderItems.hibikilegs,1), "aaa","a a","a a", 'a', RiderItems.oni_ore);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":hibikidriver"), new ResourceLocation("hibiki"),new ItemStack(RiderItems.hibikidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_ore, 'b', RiderItems.henshin_onsa);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kabukidriver"), new ResourceLocation("kabuki"),new ItemStack(RiderItems.kabukidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_orehell, 'b', RiderItems.henshin_onsa_kabuki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":toukidriver"), new ResourceLocation("touki"),new ItemStack(RiderItems.toukidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_orehell, 'b', RiderItems.henshin_onsa_touki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kiramekidriver"), new ResourceLocation("kirameki"),new ItemStack(RiderItems.kiramekidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_orehell, 'b', RiderItems.henshin_onsa_kirameki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":habatakidriver"), new ResourceLocation("habataki"),new ItemStack(RiderItems.habatakidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_orehell, 'b', RiderItems.henshin_onsa_habataki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":nishikidriver"), new ResourceLocation("nishiki"),new ItemStack(RiderItems.nishikidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_orehell, 'b', RiderItems.henshin_onsa_nishiki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kyosukedriver"), new ResourceLocation("kyoki"),new ItemStack(RiderItems.kyosukedriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_ore, 'b', RiderItems.henshin_onsa_kyoki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":dankidriver"), new ResourceLocation("danki"),new ItemStack(RiderItems.dankidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_ore, 'b', RiderItems.henshin_onsa_danki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":eikidriver"), new ResourceLocation("eiki"),new ItemStack(RiderItems.eikidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_ore, 'b', RiderItems.henshin_onsa_eiki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":goukidriver"), new ResourceLocation("gouki"),new ItemStack(RiderItems.goukidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_orehell, 'b', RiderItems.henshin_onsa_gouki);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ibukidriver"), new ResourceLocation("ibuki"),new ItemStack(RiderItems.ibukidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_ore, 'b', RiderItems.henshin_onibue_ibuki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":tokidriver"), new ResourceLocation("toki"),new ItemStack(RiderItems.tokidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_orehell, 'b', RiderItems.henshin_onibue_toki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":shoukidriver"), new ResourceLocation("shouki"),new ItemStack(RiderItems.shoukidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_ore, 'b', RiderItems.henshin_onibue_shouki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":amakidriver"), new ResourceLocation("amaki"),new ItemStack(RiderItems.amakidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_ore, 'b', RiderItems.henshin_onibue_amaki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":fubukidriver"), new ResourceLocation("fubuki"),new ItemStack(RiderItems.fubukidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_orehell, 'b', RiderItems.henshin_onibue_fubuki);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":todorokidriver"), new ResourceLocation("todoroki"),new ItemStack(RiderItems.todorokidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_ore, 'b', RiderItems.henshin_kigen_todoroki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":zankidriver"), new ResourceLocation("zanki"),new ItemStack(RiderItems.zankidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_ore, 'b', RiderItems.henshin_kigen_zanki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":shukidriver"), new ResourceLocation("shuki"),new ItemStack(RiderItems.shukidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_ore, 'b', RiderItems.henshin_kigen_shuki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":bankidriver"), new ResourceLocation("banki"),new ItemStack(RiderItems.bankidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_orehell, 'b', RiderItems.henshin_kigen_banki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":sabakidriver"), new ResourceLocation("sabaki"),new ItemStack(RiderItems.sabakidriver,1), "aaa","aba","aaa", 'a', RiderItems.oni_orehell, 'b', RiderItems.henshin_kigen_sabaki);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekibo_rekka"), new ResourceLocation("hibiki"),new ItemStack(RiderItems.ongekibo_rekka,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_onsa);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":armed_saber"), new ResourceLocation("armed_hibiki"),new ItemStack(RiderItems.armed_saber,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.unfinished_armed_saber);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekibo_yamase"), new ResourceLocation("ibuki"),new ItemStack(RiderItems.ongekibo_yamase,1), "aaa","aba","ata", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_onibue_ibuki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekibo_rakurai"), new ResourceLocation("todoroki"),new ItemStack(RiderItems.ongekibo_rakurai,1), "aaa","aba","ata", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_kigen_todoroki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekibo_shakubyoushi"), new ResourceLocation("shuki"),new ItemStack(RiderItems.ongekibo_shakubyoushi,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_kigen_shuki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekibo_nachiguro"), new ResourceLocation("danki"),new ItemStack(RiderItems.ongekibo_nachiguro,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_onsa_danki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekibo_rokushou"), new ResourceLocation("eiki"),new ItemStack(RiderItems.ongekibo_rokushou,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_onsa_eiki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekibo_gouriki"), new ResourceLocation("gouki"),new ItemStack(RiderItems.ongekibo_gouriki,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_onsa_gouki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekibo_ressui"), new ResourceLocation("kabuki"),new ItemStack(RiderItems.ongekibo_ressui,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_onsa_kabuki);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekikan_reppuu"), new ResourceLocation("ibuki"),new ItemStack(RiderItems.ongekikan_reppuu,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_onibue_ibuki);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekigen_retsurai"), new ResourceLocation("todoroki"),new ItemStack(RiderItems.ongekigen_retsurai,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_kigen_todoroki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongeki_shingen_retsuzan"), new ResourceLocation("zanki"),new ItemStack(RiderItems.ongeki_shingen_retsuzan,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_kigen_zanki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekigen_enma"), new ResourceLocation("sabaki"),new ItemStack(RiderItems.ongekigen_enma,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_kigen_sabaki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekigen_togenkyo"), new ResourceLocation("banki"),new ItemStack(RiderItems.ongekigen_togenkyo,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_kigen_banki);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":echo_sword_onsaken"), new ResourceLocation("kabuki"),new ItemStack(RiderItems.echo_sword_onsaken,1), "aaa","aba","ata", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_onsa_kabuki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekisankaku_ressetsu"), new ResourceLocation("nishiki"),new ItemStack(RiderItems.ongekisankaku_ressetsu,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_onsa_nishiki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongekikanabo_retto"), new ResourceLocation("touki"),new ItemStack(RiderItems.ongekikanabo_retto,1), "ata","aba","aaa", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_onsa_touki);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ongeki_shincho_retsuban"), new ResourceLocation("kirameki"),new ItemStack(RiderItems.ongeki_shincho_retsuban,1), "aaa","aba","ata", 'a', RiderItems.oni_ore, 'b', miscellaneousRiderItems.base_sword,'t', RiderItems.henshin_onsa_kirameki);
	
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kabutohead"), new ResourceLocation("kr_kabuto"),new ItemStack(RiderItems.kabutohead,1), "aaa","a a", 'a', RiderItems.mini_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kabutotroso"), new ResourceLocation("kr_kabuto"),new ItemStack(RiderItems.kabutotroso,1), "a a","aaa","aaa", 'a', RiderItems.mini_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kabutolegs"), new ResourceLocation("kr_kabuto"),new ItemStack(RiderItems.kabutolegs,1), "aaa","a a","a a", 'a', RiderItems.mini_zecter);
	
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kabuto_rider_belt"), new ResourceLocation("kabuto"),new ItemStack(RiderItems.kabuto_rider_belt,1), "aaa","aca","aaa", 'a', RiderItems.mini_zecter,  'c', RiderItems.kabuto_zecter);		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":thebee_rider_belt"), new ResourceLocation("thebee"),new ItemStack(RiderItems.thebee_rider_belt,1), "aaa","aca","aaa", 'a', RiderItems.mini_zecter,  'c', RiderItems.thebee_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":drake_rider_belt"), new ResourceLocation("drake"),new ItemStack(RiderItems.drake_rider_belt,1), "aaa","aca","aaa", 'a', RiderItems.mini_zecter,  'c', RiderItems.drake_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":sasword_rider_belt"), new ResourceLocation("sasword"),new ItemStack(RiderItems.sasword_rider_belt,1), "aaa","aca","aaa", 'a', RiderItems.mini_zecter,  'c', RiderItems.sasword_zecter);		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gatack_rider_belt"), new ResourceLocation("gatack"),new ItemStack(RiderItems.gatack_rider_belt,1), "aaa","aca","aaa", 'a', RiderItems.mini_zecter,  'c', RiderItems.gatack_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kickhopper_rider_belt"), new ResourceLocation("kickhopper"),new ItemStack(RiderItems.kickhopper_rider_belt,1), "aaa","aca","aaa", 'a', RiderItems.mini_zecter,  'c', RiderItems.kickhopper_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":puchhopper_rider_belt"), new ResourceLocation("punchhopper"),new ItemStack(RiderItems.puchhopper_rider_belt,1), "aaa","aca","aaa", 'a', RiderItems.mini_zecter,  'c', RiderItems.punchhopper_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":dark_kabuto_rider_belt"), new ResourceLocation("dark_kabuto"),new ItemStack(RiderItems.dark_kabuto_rider_belt,1), "aaa","aca","aaa", 'a', RiderItems.mini_zecter,  'c', RiderItems.dark_kabuto_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":hercus_rider_belt"), new ResourceLocation("hercus"),new ItemStack(RiderItems.hercus_rider_belt,1), "aaa","aca","aaa", 'a', RiderItems.unfinished_kabutick_zecter,  'c', RiderItems.hercus_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ketaros_rider_belt"), new ResourceLocation("ketaros"),new ItemStack(RiderItems.ketaros_rider_belt,1), "aaa","aca","aaa", 'a', RiderItems.unfinished_kabutick_zecter,  'c', RiderItems.ketaros_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":caucasus_rider_belt"), new ResourceLocation("caucasus"),new ItemStack(RiderItems.caucasus_rider_belt,1), "aaa","aca","aaa", 'a', RiderItems.unfinished_kabutick_zecter,  'c', RiderItems.caucasus_zecter);
	
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kabuto_kunai"), new ResourceLocation("kabuto"),new ItemStack(RiderItems.kabuto_kunai,1), "ama","aba","aaa", 'a', RiderItems.mini_zecter, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.kabuto_zecter);
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":kabuto_kunai_kunai"),new ResourceLocation("kabuto"),new ItemStack(RiderItems.kabuto_kunai_kunai), new Ingredient[]{Ingredient.fromItem(RiderItems.kabuto_kunai)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":kabuto_kunai2"),new ResourceLocation("kabuto"),new ItemStack(RiderItems.kabuto_kunai), new Ingredient[]{Ingredient.fromItem(RiderItems.kabuto_kunai_kunai)});	
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gatack_double_calibur"), new ResourceLocation("gatack"),new ItemStack(RiderItems.gatack_double_calibur,1), "ama","aba","aaa", 'a', RiderItems.mini_zecter, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.gatack_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gatack_double_calibur_minus"), new ResourceLocation("gatack"),new ItemStack(RiderItems.gatack_double_calibur_minus,1), "aaa","aba","ama", 'a', RiderItems.mini_zecter, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.gatack_zecter);
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gatack_double_calibur_twin"),new ResourceLocation("gatack"),new ItemStack(RiderItems.gatack_double_calibur_twin), new Ingredient[]{Ingredient.fromItem(RiderItems.gatack_double_calibur),Ingredient.fromItem(RiderItems.gatack_double_calibur_minus)});			
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":sasword_yaiver"), new ResourceLocation("sasword"),new ItemStack(RiderItems.sasword_yaiver,1), "ama","aba","aaa", 'a', RiderItems.mini_zecter, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.sasword_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":drake_grip"), new ResourceLocation("drake"),new ItemStack(RiderItems.drake_grip,1), "ama","aba","aaa", 'a', RiderItems.mini_zecter, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.drake_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":zect_kunai"), new ResourceLocation("dark_kabuto"),new ItemStack(RiderItems.zect_kunai,1), "ama","aba","aaa", 'a', RiderItems.mini_zecter, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.dark_kabuto_zecter);
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":zect_kunai_kunai"),new ResourceLocation("dark_kabuto"),new ItemStack(RiderItems.zect_kunai_kunai), new Ingredient[]{Ingredient.fromItem(RiderItems.zect_kunai)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":zect_kunai2"),new ResourceLocation("dark_kabuto"),new ItemStack(RiderItems.zect_kunai), new Ingredient[]{Ingredient.fromItem(RiderItems.zect_kunai_kunai)});	
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":clock_up_pad"), new ResourceLocation("kr_kabuto"),new ItemStack(RiderItems.clock_up_pad,1), "aaa","aba","aaa", 'a', RiderItems.mini_zecter, 'b', Blocks.IRON_BLOCK);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":zect_mizer"), new ResourceLocation("kr_kabuto"),new ItemStack(RiderItems.zect_mizer,1), "aaa","aba","aaa", 'a', RiderItems.mini_zecter, 'b', miscellaneousRiderItems.base_sword);		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":perfect_zecter"), new ResourceLocation("kabuto_hyper"),new ItemStack(RiderItems.perfect_zecter,1), "ama","cba","ada", 'a', RiderItems.mini_zecter, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.perfectdrake_zecter, 'c', RiderItems.perfectthebee_zecter, 'd', RiderItems.perfectsasword_zecter);
	
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kivahead"), new ResourceLocation("kr_kiva"),new ItemStack(RiderItems.kivahead,1), "aaa","a a", 'a', RiderItems.fuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kivatroso"), new ResourceLocation("kr_kiva"),new ItemStack(RiderItems.kivatroso,1), "a a","aaa","aaa", 'a', RiderItems.fuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kivalegs"), new ResourceLocation("kr_kiva"),new ItemStack(RiderItems.kivalegs,1), "aaa","a a","a a", 'a', RiderItems.fuestle);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kivadriver"), new ResourceLocation("kiva"),new ItemStack(RiderItems.kivadriver,1), "aaa","aca","aaa", 'a', RiderItems.fuestle,  'c', RiderItems.wakeupfuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ixa_belt"), new ResourceLocation("ixa"),new ItemStack(RiderItems.ixa_belt,1), "aaa","aca","aaa", 'a', RiderItems.fuestlefake,  'c', RiderItems.knucklefuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":sagarc_belt"), new ResourceLocation("saga"),new ItemStack(RiderItems.sagarc_belt,1), "aaa","aca","aaa", 'a', RiderItems.fuestle,  'c', RiderItems.sagafuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":arcdriver"), new ResourceLocation("arc"),new ItemStack(RiderItems.arcdriver,1), "aca","aaa","aaa", 'a', RiderItems.fuestlefake,  'c', RiderItems.keyfuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":reydriver"), new ResourceLocation("rey"),new ItemStack(RiderItems.reydriver,1), "aaa","aaa","aca", 'a', RiderItems.fuestlefake,  'c', RiderItems.keyfuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":darkkivadriver"), new ResourceLocation("dark_kiva"),new ItemStack(RiderItems.darkkivadriver,1), "aaa","aca","aaa", 'a', RiderItems.fuestle,  'c', RiderItems.darkwakeupfuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":newkivadriver"), new ResourceLocation("new_kiva"),new ItemStack(RiderItems.newkivadriver,1), "aaa","aca","aaa", 'a', RiderItems.fuestle,  'c', RiderItems.newwakeupfuestle);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":garulu_saber"), new ResourceLocation("kiva_garulu"),new ItemStack(RiderItems.garulu_saber,1), "ama","aba","aaa", 'a', RiderItems.fuestle, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.garulufuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":basshaamagnum"), new ResourceLocation("kiva_basshaa"),new ItemStack(RiderItems.basshaamagnum,1), "ama","aba","aaa", 'a', RiderItems.fuestle, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.basshaafuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":dogga_hammer"), new ResourceLocation("kiva_dogga"),new ItemStack(RiderItems.dogga_hammer,1), "ama","aba","aaa", 'a', RiderItems.fuestle, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.doggafuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":zanbatsword_core"), new ResourceLocation("kiva_emperor"),new ItemStack(RiderItems.zanbatsword_core,1), "ama","aba","aaa", 'a', RiderItems.fuestle, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.fuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":zanbatsword"), new ResourceLocation("kiva_emperor"),new ItemStack(RiderItems.zanbatsword,1), "ama","aba","aaa", 'a', RiderItems.fuestle, 'b', RiderItems.zanbatsword_core, 'm', RiderItems.tatsulot);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ixa_caliber"), new ResourceLocation("ixa"),new ItemStack(RiderItems.ixa_caliber,1), "ama","aba","aaa", 'a', RiderItems.fuestle, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.knucklefuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ixariser"), new ResourceLocation("rising_ixa"),new ItemStack(RiderItems.ixariser,1), "ama","aba","aaa", 'a', RiderItems.fuestle, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.risingfuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":jacorder"), new ResourceLocation("saga"),new ItemStack(RiderItems.jacorder,1), "ama","aba","aaa", 'a', RiderItems.fuestle, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.sagafuestle);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":decadehead"), new ResourceLocation("kr_decade"),new ItemStack(RiderItems.decadehead,1), "aaa","a a", 'a', RiderItems.blankcard);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":decadetroso"), new ResourceLocation("kr_decade"),new ItemStack(RiderItems.decadetroso,1), "a a","aaa","aaa", 'a', RiderItems.blankcard);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":decadelegs"), new ResourceLocation("kr_decade"),new ItemStack(RiderItems.decadelegs,1), "aaa","a a","a a", 'a', RiderItems.blankcard);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":decadedriver"), new ResourceLocation("decade"),new ItemStack(RiderItems.decadedriver,1), "aaa","aca","aaa", 'a', RiderItems.blankcard, 'c', RiderItems.decadecard);		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":diend_driver"), new ResourceLocation("diend"),new ItemStack(RiderItems.diend_driver,1), "aca","aba","aaa", 'a', RiderItems.blankcard, 'b', miscellaneousRiderItems.base_sword, 'c', RiderItems.diendcard);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":dark_decadedriver"), new ResourceLocation("dark_decade"),new ItemStack(RiderItems.dark_decadedriver,1), "aaa","aca","aaa", 'a', RiderItems.blankcard, 'c', RiderItems.darkdecadecard);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ride_booker"), new ResourceLocation("decade"),new ItemStack(RiderItems.ride_booker,1), "ama","aba","aaa", 'a', RiderItems.blankcard, 'b', miscellaneousRiderItems.base_sword, 'm', RiderItems.decadecard);
		
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":ongekibo_rekka_decade"),new ResourceLocation("decade"),new ItemStack(RiderItems.ongekibo_rekka_decade), new Ingredient[]{Ingredient.fromItem(RiderItems.decadecard),Ingredient.fromItem(RiderItems.ongekibo_rekka)});
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":ongekibo_rekka_diend"),new ResourceLocation("diend"),new ItemStack(RiderItems.ongekibo_rekka_diend), new Ingredient[]{Ingredient.fromItem(RiderItems.diendcard),Ingredient.fromItem(RiderItems.ongekibo_rekka)});
		
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":dragon_kuugacard"),new ResourceLocation("form_ride_card"),new ItemStack(RiderItems.dragon_kuugacard), new Ingredient[]{Ingredient.fromItem(RiderItems.kuugacard),Ingredient.fromItem(RiderItems.kuuga_dragon)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":pegasus_kuugacard"),new ResourceLocation("form_ride_card"),new ItemStack(RiderItems.pegasus_kuugacard), new Ingredient[]{Ingredient.fromItem(RiderItems.kuugacard),Ingredient.fromItem(RiderItems.kuuga_pegasus)});		
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":titan_kuugacard"),new ResourceLocation("form_ride_card"),new ItemStack(RiderItems.titan_kuugacard), new Ingredient[]{Ingredient.fromItem(RiderItems.kuugacard),Ingredient.fromItem(RiderItems.kuuga_titan)});	
		
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":storm_agitocard"),new ResourceLocation("form_ride_card"),new ItemStack(RiderItems.storm_agitocard), new Ingredient[]{Ingredient.fromItem(RiderItems.agitocard),Ingredient.fromItem(RiderItems.agito_storm)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":flame_agitocard"),new ResourceLocation("form_ride_card"),new ItemStack(RiderItems.flame_agitocard), new Ingredient[]{Ingredient.fromItem(RiderItems.agitocard),Ingredient.fromItem(RiderItems.agito_flame)});	
		
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":axel_faizcard"),new ResourceLocation("form_ride_card"),new ItemStack(RiderItems.axel_faizcard), new Ingredient[]{Ingredient.fromItem(RiderItems.faizcard),Ingredient.fromItem(RiderItems.faiz_axel_mission_memory)});	
		
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":rod_den_ocard"),new ResourceLocation("form_ride_card"),new ItemStack(RiderItems.rod_den_ocard), new Ingredient[]{Ingredient.fromItem(RiderItems.den_ocard),Ingredient.fromItem(RiderItems.rider_ticket_rod)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":axe_den_ocard"),new ResourceLocation("form_ride_card"),new ItemStack(RiderItems.axe_den_ocard), new Ingredient[]{Ingredient.fromItem(RiderItems.den_ocard),Ingredient.fromItem(RiderItems.rider_ticket_ax)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gun_den_ocard"),new ResourceLocation("form_ride_card"),new ItemStack(RiderItems.gun_den_ocard), new Ingredient[]{Ingredient.fromItem(RiderItems.den_ocard),Ingredient.fromItem(RiderItems.rider_ticket_gun)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":wing_den_ocard"),new ResourceLocation("form_ride_card"),new ItemStack(RiderItems.wing_den_ocard), new Ingredient[]{Ingredient.fromItem(RiderItems.den_ocard),Ingredient.fromItem(RiderItems.rider_ticket_wing)});	
		
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":garulu_kivacard"),new ResourceLocation("form_ride_card"),new ItemStack(RiderItems.garulu_kivacard), new Ingredient[]{Ingredient.fromItem(RiderItems.kivacard),Ingredient.fromItem(RiderItems.garulufuestle)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":basshaa_kivacard"),new ResourceLocation("form_ride_card"),new ItemStack(RiderItems.basshaa_kivacard), new Ingredient[]{Ingredient.fromItem(RiderItems.kivacard),Ingredient.fromItem(RiderItems.basshaafuestle)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":dogga_kivacard"),new ResourceLocation("form_ride_card"),new ItemStack(RiderItems.dogga_kivacard), new Ingredient[]{Ingredient.fromItem(RiderItems.kivacard),Ingredient.fromItem(RiderItems.doggafuestle)});	
		
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":ultimate_kuugacard"),new ResourceLocation("final_form_ride_card"),new ItemStack(RiderItems.ultimate_kuugacard), new Ingredient[]{Ingredient.fromItem(RiderItems.kuugacard),Ingredient.fromItem(RiderItems.kuuga_ultimate)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":shining_agitocard"),new ResourceLocation("final_form_ride_card"),new ItemStack(RiderItems.shining_agitocard), new Ingredient[]{Ingredient.fromItem(RiderItems.agitocard),Ingredient.fromItem(RiderItems.agito_shining)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":survive_ryukicard"),new ResourceLocation("final_form_ride_card"),new ItemStack(RiderItems.survive_ryukicard), new Ingredient[]{Ingredient.fromItem(RiderItems.ryukicard),Ingredient.fromItem(RiderItems.survive_advent)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":blaster_faizcard"),new ResourceLocation("final_form_ride_card"),new ItemStack(RiderItems.blaster_faizcard), new Ingredient[]{Ingredient.fromItem(RiderItems.faizcard),Ingredient.fromItem(RiderItems.faiz_blaster_mission_memory)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":king_bladecard"),new ResourceLocation("final_form_ride_card"),new ItemStack(RiderItems.king_bladecard), new Ingredient[]{Ingredient.fromItem(RiderItems.bladecard_de),Ingredient.fromItem(RiderItems.evolution_caucasus)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":armed_hibikicard"),new ResourceLocation("final_form_ride_card"),new ItemStack(RiderItems.armed_hibikicard), new Ingredient[]{Ingredient.fromItem(RiderItems.hibikicard),Ingredient.fromItem(RiderItems.armed_saber)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":hyper_kabutocard"),new ResourceLocation("final_form_ride_card"),new ItemStack(RiderItems.hyper_kabutocard), new Ingredient[]{Ingredient.fromItem(RiderItems.kabutocard),Ingredient.fromItem(RiderItems.hyper_zecter)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":liner_den_ocard"),new ResourceLocation("final_form_ride_card"),new ItemStack(RiderItems.liner_den_ocard), new Ingredient[]{Ingredient.fromItem(RiderItems.denkamen_sword),Ingredient.fromItem(RiderItems.den_ocard)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":emperor_kivacard"),new ResourceLocation("final_form_ride_card"),new ItemStack(RiderItems.emperor_kivacard), new Ingredient[]{Ingredient.fromItem(RiderItems.kivacard),Ingredient.fromItem(RiderItems.tatsulot)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":k_touch"),new ResourceLocation("decade_complete"),new ItemStack(RiderItems.k_touch), new Ingredient[]{Ingredient.fromItem(RiderItems.ultimate_kuugacard),Ingredient.fromItem(RiderItems.shining_agitocard),Ingredient.fromItem(RiderItems.survive_ryukicard),Ingredient.fromItem(RiderItems.blaster_faizcard),Ingredient.fromItem(RiderItems.king_bladecard),Ingredient.fromItem(RiderItems.armed_hibikicard),Ingredient.fromItem(RiderItems.hyper_kabutocard),Ingredient.fromItem(RiderItems.liner_den_ocard),Ingredient.fromItem(RiderItems.emperor_kivacard)});	
		
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":g4card"),new ResourceLocation("kamen_ride_card"),new ItemStack(RiderItems.g4card), new Ingredient[]{Ingredient.fromItem(RiderItems.blankcard),Ingredient.fromItem(RiderItems.g4)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":ryugacard"),new ResourceLocation("kamen_ride_card"),new ItemStack(RiderItems.ryugacard), new Ingredient[]{Ingredient.fromItem(RiderItems.blankcard),Ingredient.fromItem(RiderItems.dragblacker_advent)});			
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":orgacard"),new ResourceLocation("kamen_ride_card"),new ItemStack(RiderItems.orgacard), new Ingredient[]{Ingredient.fromItem(RiderItems.blankcard),Ingredient.fromItem(RiderItems.orga_mission_memory)});			
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":glaivecard"),new ResourceLocation("kamen_ride_card"),new ItemStack(RiderItems.glaivecard), new Ingredient[]{Ingredient.fromItem(RiderItems.blankcard),Ingredient.fromItem(RiderItems.changekerberosglaive)});			
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":kabukicard"),new ResourceLocation("kamen_ride_card"),new ItemStack(RiderItems.kabukicard), new Ingredient[]{Ingredient.fromItem(RiderItems.blankcard),Ingredient.fromItem(RiderItems.henshin_onsa_kabuki)});			
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":caucasuscard"),new ResourceLocation("kamen_ride_card"),new ItemStack(RiderItems.caucasuscard), new Ingredient[]{Ingredient.fromItem(RiderItems.blankcard),Ingredient.fromItem(RiderItems.caucasus_zecter)});			
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":arccard"),new ResourceLocation("kamen_ride_card"),new ItemStack(RiderItems.arccard), new Ingredient[]{Ingredient.fromItem(RiderItems.blankcard),Ingredient.fromItem(RiderItems.keyfuestle)});			
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":skullcard"),new ResourceLocation("kamen_ride_card"),new ItemStack(RiderItems.skullcard), new Ingredient[]{Ingredient.fromItem(RiderItems.blankcard),Ingredient.fromItem(RiderItems.skull_memory)});			
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":k_touch_diend"),new ResourceLocation("diend_complete"),new ItemStack(RiderItems.k_touch_diend), new Ingredient[]{Ingredient.fromItem(RiderItems.g4card),Ingredient.fromItem(RiderItems.ryugacard),Ingredient.fromItem(RiderItems.orgacard),Ingredient.fromItem(RiderItems.glaivecard),Ingredient.fromItem(RiderItems.kabukicard),Ingredient.fromItem(RiderItems.caucasuscard),Ingredient.fromItem(RiderItems.arccard),Ingredient.fromItem(RiderItems.skullcard)});	

		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":drivehead"), new ResourceLocation("kr_drive"),new ItemStack(RiderItems.drivehead,1), "aaa","a a", 'a', RiderItems.proto_speedshift);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":drivetroso"), new ResourceLocation("kr_drive"),new ItemStack(RiderItems.drivetroso,1), "a a","aaa","aaa", 'a',RiderItems.proto_speedshift);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":drivelegs"), new ResourceLocation("kr_drive"),new ItemStack(RiderItems.drivelegs,1), "aaa","a a","a a", 'a', RiderItems.proto_speedshift);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":drivedriver"), new ResourceLocation("drive"),new ItemStack(RiderItems.drivedriver,1), "aaa","aca","aaa", 'a', RiderItems.proto_speedshift, 'c', RiderItems.speedshift);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mach_driver_honoh"), new ResourceLocation("mach"),new ItemStack(RiderItems.mach_driver_honoh,1), "aaa","aca","aaa", 'a', RiderItems.signal_chaser, 'c', RiderItems.signal_mach);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":metro_pd_driver_honoh"), new ResourceLocation("jun"),new ItemStack(RiderItems.metro_pd_driver_honoh,1), "aaa","aca","aaa", 'a', RiderItems.signal_chaser, 'c', RiderItems.tokujoka_key);		
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":break_gunner"), new ResourceLocation("mashin_chaser"),new ItemStack(RiderItems.break_gunner,1), "ama","aba","aaa", 'a', RiderItems.proto_speedshift, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.proto_speedshift);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":lupin_gunner"), new ResourceLocation("lupin"),new ItemStack(RiderItems.lupin_gunner,1), "ama","aba","aaa", 'a', RiderItems.proto_speedshift, 'b', miscellaneousRiderItems.base_sword, 'm',  Blocks.GOLD_BLOCK);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":proto_drivedriver"), new ResourceLocation("proto_drive"),new ItemStack(RiderItems.proto_drivedriver,1), "aaa","aca","aaa", 'a', RiderItems.proto_speedshift, 'c', RiderItems.proto_speedshift);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mach_driver_honoh_chaser"), new ResourceLocation("chaser"),new ItemStack(RiderItems.mach_driver_honoh_chaser,1), "aaa","aca","aaa", 'a', RiderItems.signal_chaser, 'c', RiderItems.signal_chaser);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mach_driver_honoh_drive"), new ResourceLocation("drive"),new ItemStack(RiderItems.mach_driver_honoh_drive,1), "aaa","aca","aaa", 'a', RiderItems.signal_chaser, 'c', RiderItems.tridoron_key);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":drivedriver_dark"), new ResourceLocation("dark_drive"),new ItemStack(RiderItems.drivedriver_dark,1), "aaa","aca","aaa", 'a', RiderItems.proto_speedshift, 'c', RiderItems.shift_next);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":drivedriverhart"), new ResourceLocation("heart"),new ItemStack(RiderItems.drivedriverhart,1), "aaa","aca","aaa", 'a', RiderItems.proto_speedshift, 'c', RiderItems.heartronshift);
		
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":handle_sword"), new ResourceLocation("drive_wild"),new ItemStack(RiderItems.handle_sword,1), "ama","aba","aaa", 'a', RiderItems.proto_speedshift, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.wildshift);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":door_ju"), new ResourceLocation("drive_technique"),new ItemStack(RiderItems.door_ju,1), "ama","aba","aaa", 'a', RiderItems.proto_speedshift, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.techniqueshift);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":trailer_hou"), new ResourceLocation("drive_formula"),new ItemStack(RiderItems.trailer_hou,1), "ama","aba","aaa", 'a', RiderItems.proto_speedshift, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.formulashift);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":zenrin_shooter"), new ResourceLocation("mach"),new ItemStack(RiderItems.zenrin_shooter,1), "ama","aba","aaa", 'a', RiderItems.proto_speedshift, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.signal_mach);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":blade_gunner"), new ResourceLocation("dark_drive"),new ItemStack(RiderItems.blade_gunner,1), "ama","aba","aaa", 'a', RiderItems.proto_speedshift, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.shift_next);	
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":shingouax"), new ResourceLocation("chaser"),new ItemStack(RiderItems.shingouax,1), "ama","aba","aaa", 'a', RiderItems.proto_speedshift, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.signal_chaser);
				
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ghosthead"), new ResourceLocation("kr_ghost"),new ItemStack(RiderItems.ghosthead,1), "aaa","a a", 'a', RiderItems.ghost_icons);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ghosttroso"), new ResourceLocation("kr_ghost"),new ItemStack(RiderItems.ghosttroso,1), "a a","aaa","aaa", 'a',RiderItems.ghost_icons);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ghostlegs"), new ResourceLocation("kr_ghost"),new ItemStack(RiderItems.ghostlegs,1), "aaa","a a","a a", 'a', RiderItems.ghost_icons);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ghostdriver"), new ResourceLocation("ghost"),new ItemStack(RiderItems.ghostdriver,1), "aaa","aca","aaa", 'a', RiderItems.ghost_icons,  'c', RiderItems.ore_ghost_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":specterdriver"), new ResourceLocation("specter"),new ItemStack(RiderItems.specterdriver,1), "aaa","aca","aaa", 'a', RiderItems.ghost_icons,  'c', RiderItems.specter_ghost_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":dark_ghostdriver"), new ResourceLocation("dark_ghost"),new ItemStack(RiderItems.dark_ghostdriver,1), "aaa","aca","aaa", 'a', RiderItems.ghost_icons,  'c', RiderItems.dark_ghost_icon);		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":zero_specterdriver"), new ResourceLocation("zero_specter"),new ItemStack(RiderItems.zero_specterdriver,1), "aaa","aca","aaa", 'a', RiderItems.ghost_icons,  'c', RiderItems.zero_specter_ghost_icon);		

		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mega_ulorder"), new ResourceLocation("necrom"),new ItemStack(RiderItems.mega_ulorder,1), "aaa","aca","aaa", 'a', RiderItems.ghost_gammaicons,  'c', RiderItems.necrom_ghost_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":proto_mega_ulorder_b"), new ResourceLocation("dark_necrom"),new ItemStack(RiderItems.proto_mega_ulorder_b,1), "aaa","aca","aaa", 'a', RiderItems.ghost_gammaicons,  'c', RiderItems.dark_necrom_blue_ghost_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":proto_mega_ulorder_r"), new ResourceLocation("dark_necrom"),new ItemStack(RiderItems.proto_mega_ulorder_r,1), "aaa","aca","aaa", 'a', RiderItems.ghost_gammaicons,  'c', RiderItems.dark_necrom_red_ghost_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":proto_mega_ulorder_y"), new ResourceLocation("dark_necrom"),new ItemStack(RiderItems.proto_mega_ulorder_y,1), "aaa","aca","aaa", 'a', RiderItems.ghost_gammaicons,  'c', RiderItems.dark_necrom_yellow_ghost_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":proto_mega_ulorder_p"), new ResourceLocation("dark_necrom"),new ItemStack(RiderItems.proto_mega_ulorder_p,1), "aaa","aca","aaa", 'a', RiderItems.ghost_gammaicons,  'c', RiderItems.dark_necrom_pink_ghost_icon);		
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":unfinished_eyecon_driver_g"),new ResourceLocation("ghost_greatful"),new ItemStack(RiderItems.unfinished_eyecon_driver_g), new Ingredient[]{Ingredient.fromItem(RiderItems.musashi_ghost_icon),Ingredient.fromItem(RiderItems.edison_ghost_icon),Ingredient.fromItem(RiderItems.robin_ghost_icon),Ingredient.fromItem(RiderItems.newton_ghost_icon),Ingredient.fromItem(RiderItems.billy_the_kid_icon),Ingredient.fromItem(RiderItems.beethoven_icon),Ingredient.fromItem(RiderItems.benkei_icon),Ingredient.fromItem(RiderItems.ryoma_icon),Ingredient.fromItem(RiderItems.goemon_icon)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":eyecon_driver_g"),new ResourceLocation("ghost_greatful"),new ItemStack(RiderItems.eyecon_driver_g), new Ingredient[]{Ingredient.fromItem(RiderItems.unfinished_eyecon_driver_g),Ingredient.fromItem(RiderItems.himiko_ghost_icon),Ingredient.fromItem(RiderItems.nobunaga_icon),Ingredient.fromItem(RiderItems.tutankhamun_icon),Ingredient.fromItem(RiderItems.houdini_icon),Ingredient.fromItem(RiderItems.sanzo_icon),Ingredient.fromItem(RiderItems.grimm_icon)});			
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gan_gun_saber_blade"), new ResourceLocation("ghost"),new ItemStack(RiderItems.gan_gun_saber_blade,1), "ama","aba","aaa", 'a', RiderItems.ghost_icons, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.ore_ghost_icon);		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gan_gun_saber_gun"), new ResourceLocation("ghost_edison"),new ItemStack(RiderItems.gan_gun_saber_gun,1), "ama","aba","aaa", 'a', RiderItems.ghost_icons, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.edison_ghost_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gan_gun_saber_nitouryu"), new ResourceLocation("ghost_musashi"),new ItemStack(RiderItems.gan_gun_saber_nitouryu,1), "ama","aba","aaa", 'a', RiderItems.ghost_icons, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.musashi_ghost_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gan_gun_saber_condor_denwor"), new ResourceLocation("ghost_robin_hood"),new ItemStack(RiderItems.gan_gun_saber_condor_denwor,1), "ama","aba","aaa", 'a', RiderItems.ghost_icons, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.robin_ghost_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gan_gun_saber_naginata"), new ResourceLocation("ghost_newton"),new ItemStack(RiderItems.gan_gun_saber_naginata,1), "ama","aba","aaa", 'a', RiderItems.ghost_icons, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.newton_ghost_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gan_gun_saber_rifle"), new ResourceLocation("ghost_billy_the_kid"),new ItemStack(RiderItems.gan_gun_saber_rifle,1), "ama","aba","aaa", 'a', RiderItems.ghost_icons, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.billy_the_kid_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gan_gun_saber_hammer"), new ResourceLocation("ghost_benkei"),new ItemStack(RiderItems.gan_gun_saber_hammer,1), "ama","aba","aaa", 'a', RiderItems.ghost_icons, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.benkei_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gan_gun_saber_nitouryu_2"), new ResourceLocation("ghost_beethoven"),new ItemStack(RiderItems.gan_gun_saber_nitouryu_2,1), "ama","aba","aaa", 'a', RiderItems.ghost_icons, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.beethoven_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":sunglasseslasher_sword"), new ResourceLocation("ghost_boost"),new ItemStack(RiderItems.sunglasseslasher_sword,1), "ama","aba","aaa", 'a', RiderItems.ghost_icons, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.toucon_boost_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gan_gun_hand_rod"), new ResourceLocation("specter"),new ItemStack(RiderItems.gan_gun_hand_rod,1), "ama","aba","aaa", 'a', RiderItems.ghost_icons, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.specter_ghost_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gan_gun_hand_kama"), new ResourceLocation("specter_tutankhamun"),new ItemStack(RiderItems.gan_gun_hand_kama,1), "ama","aba","aaa", 'a', RiderItems.ghost_icons, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.tutankhamun_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":deep_slasher_sword"), new ResourceLocation("deep_specter"),new ItemStack(RiderItems.deep_slasher_sword,1), "ama","aba","aaa", 'a', RiderItems.ghost_icons, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.deep_specter_ghost_icon);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gan_gun_catcher_rod"), new ResourceLocation("necrom"),new ItemStack(RiderItems.gan_gun_catcher_rod,1), "ama","aba","aaa", 'a', RiderItems.ghost_icons, 'b', miscellaneousRiderItems.base_sword, 'm',  RiderItems.necrom_ghost_icon);
		
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kuuga_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.kuuga_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.kuuga_mighty);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":agito_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.agito_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.agito_ground);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ryuki_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.ryuki_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.dragreder_advent);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":faiz_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.faiz_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.faiz_mission_memory);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":blade_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.blade_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.changebeetle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":hibiki_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.hibiki_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.henshin_onsa);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kabuto_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.kabuto_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.kabuto_zecter);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":den_o_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.den_o_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.rider_ticket_sword);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kiva_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.kiva_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.wakeupfuestle);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":decade_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.decade_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.decadecard);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":double_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.double_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.joker_memory);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ooo_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.ooo_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.taka);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":fourze_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.fourze_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.rocket_swich);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":wizard_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.wizard_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.flame_ring);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gaim_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.gaim_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.orange_lockseed);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":drive_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.drive_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.speedshift);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ghost_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.ghost_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ore_ghost_icon, 'b', RiderItems.ghost_icons);
		GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ex_aid_ghost_icon"), new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.ex_aid_ghost_icon,1), "aaa","aba","aaa", 'a', RiderItems.ghost_icons, 'b', RiderItems.mighty_action_x_gashat);
	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":unfinished_fourtyfive_heisei_ghost_icon"),new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.unfinished_fourtyfive_heisei_ghost_icon), new Ingredient[]{Ingredient.fromItem(RiderItems.kuuga_ghost_icon),Ingredient.fromItem(RiderItems.agito_ghost_icon),Ingredient.fromItem(RiderItems.ryuki_ghost_icon),Ingredient.fromItem(RiderItems.faiz_ghost_icon),Ingredient.fromItem(RiderItems.blade_ghost_icon),Ingredient.fromItem(RiderItems.hibiki_ghost_icon),Ingredient.fromItem(RiderItems.kabuto_ghost_icon),Ingredient.fromItem(RiderItems.den_o_ghost_icon),Ingredient.fromItem(RiderItems.kiva_ghost_icon)});	
		GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":fourtyfive_heisei_ghost_icon"),new ResourceLocation("legend_eyecon"),new ItemStack(RiderItems.fourtyfive_heisei_ghost_icon), new Ingredient[]{Ingredient.fromItem(RiderItems.unfinished_fourtyfive_heisei_ghost_icon),Ingredient.fromItem(RiderItems.decade_ghost_icon),Ingredient.fromItem(RiderItems.double_ghost_icon),Ingredient.fromItem(RiderItems.ooo_ghost_icon),Ingredient.fromItem(RiderItems.fourze_ghost_icon),Ingredient.fromItem(RiderItems.wizard_ghost_icon),Ingredient.fromItem(RiderItems.gaim_ghost_icon),Ingredient.fromItem(RiderItems.drive_ghost_icon),Ingredient.fromItem(RiderItems.ghost_ghost_icon)});	
		
		GameRegistry.addSmelting(new ItemStack(RiderItems.dragon_sclashjelly),new ItemStack(RiderItems.dragon_magma_full_bottle), 1);

		GameRegistry.addSmelting(new ItemStack(RiderBlocks.ginga_meteor),new ItemStack(RiderItems.solu_switch), 1);

		GameRegistry.addSmelting(new ItemStack(RiderItems.cellmedal),new ItemStack(RiderItems.cell_alloy_ingot), 1);
		GameRegistry.addSmelting(new ItemStack(RiderItems.purple_medals_empty),new ItemStack(Blocks.STONE), 1);
		
		if (Item.getByNameOrId("supersentaicraft:red_ryusoul") != null){
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":ryusoulger_ridewatch"),new ResourceLocation("kr_sentai"),new ItemStack(RiderItems.ryusoulger_ridewatch), new Ingredient[]{Ingredient.fromItem(RiderItems.blank_watch),Ingredient.fromItem(Item.getByNameOrId("supersentaicraft:red_ryusoul"))});
		}		
	

	VillagerRegistry.VillagerProfession librarian=ForgeRegistries.VILLAGER_PROFESSIONS.getValue(new ResourceLocation("minecraft:librarian"));
	librarian.getCareer(5).addTrade(1,new Rider_trades());
	}
}
