
modLoader="javafml"
loaderVersion="[45,)" 
license="WTFPL"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" 

[[mods]]
modId="kamenridercraft" #mandatory
version="${file.jarVersion}"
displayName="Kamen Rider Craft" 
#updateJSONURL="https://change.me.example.invalid/updates.json" 
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="krc.png"
credits="Those on the Discord who helped with various textures."
authors="Kelco_K22, Trainfanz, LiasDan" 

description='''
Since 1971, The Kamen Rider Series has captivated people across the world with it's stories, characters, and it's 'tokusatsu' production techniques. Now, nearly 50 years of Japanese cultural icons arrives in Minecraft!
Kamen Rider Craft began as a small project in late 2012 by Kelco_K22, and has since evolved into a spawling mod with hundreds of items, weapons, and forms with multiple developers on board.
Collect items, assemble an arsenal of armors and weapons, and fight a variety of new mobs and bosses! Every series and era of Kamen Rider is represented in some form, including toy-exclusive and extra-canonical items!
'''

[[dependencies.kamenridercraft]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[44,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.kamenridercraft]] #optional
    modId="geckolib" #mandatory
    mandatory=true #mandatory
    versionRange="[4.1.3,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.kamenridercraft]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19.3,1.21)"
    ordering="NONE"
    side="BOTH"
