// Date: 24/08/2013 15:36:02
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Kamen_Rider_Craft_4TH.model;

import org.lwjgl.opengl.GL11;
import Kamen_Rider_Craft_4TH.util.Refercence;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Items;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.EnumAction;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;


public class ImaginSandModel extends ModelBiped
{


	public ImaginSandModel()
	{

	}
	
	
	
	public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
	{
	    this.setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);

	    {
	    	this.bipedBody.offsetY=+0.75f;
	    	this.bipedLeftArm.offsetY=+0.75f;
	    	this.bipedRightArm.offsetY=+0.75f;
	    	this.bipedHead.offsetY=+0.75f;
	    	this.bipedHeadwear.offsetY=+0.75f;

	        this.bipedRightLeg.offsetY=-1.25f;
	        this.bipedLeftLeg.offsetY=-1.25f;
	    	
	        this.bipedBody.render(par7);
	        this.bipedHead.render(par7);
	        this.bipedHeadwear.render(par7);
	        this.bipedRightArm.render(par7);
	        this.bipedLeftArm.render(par7);
	        this.bipedRightLeg.render(par7);
	        this.bipedLeftLeg.render(par7);

	        
	    }
	}
	

	public void setRotationAngles(float p_78087_1_, float p_78087_2_, float p_78087_3_, float p_78087_4_, float p_78087_5_, float p_78087_6_, Entity p_78087_7_)
	{
		super.setRotationAngles(p_78087_1_, p_78087_2_, p_78087_3_, p_78087_4_, p_78087_5_, p_78087_6_, p_78087_7_);


	}



}

