// Date: 27/05/2015 23:35:12
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package Kamen_Rider_Craft_4TH.model;

import org.lwjgl.opengl.GL11;

import Kamen_Rider_Craft_4TH.RiderItems;
import Kamen_Rider_Craft_4TH.ShowaRiderItems;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.item.EntityItem;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Items;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.EnumAction;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class model_belt_w extends ModelBiped
{
	//fields
	

	public ItemStack belt;
	public ItemStack wings=new ItemStack(ShowaRiderItems.blanknoitem);



	public model_belt_w()
	{
		textureWidth = 64;
		textureHeight = 128;


	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		if (entity instanceof EntityLivingBase){
			EntityLivingBase living = ((EntityLivingBase)entity);
			ItemStack stack = living.getItemStackFromSlot(EntityEquipmentSlot.FEET);
			
			GL11.glPushMatrix();
			GL11.glPushMatrix();
			if (stack.hasTagCompound()){
			if (stack.getTagCompound().getInteger("core2")==2&stack.getItem()== RiderItems.Wdriver){
				wings=new ItemStack(RiderItems.cyclone_joker_gold_xtreme_wings);
			}else{
				wings=new ItemStack(ShowaRiderItems.blanknoitem);
			}
			if(living.isSneaking()){
				GL11.glRotatef(20, 1, 0, 0);	
			}
			}
			GL11.glRotatef(180, 0, 1, 0);
			GL11.glRotatef(180, 0, 0, 1);
			GL11.glScaled(3,3,1);
			GL11.glTranslatef((float) (0f),-0.05f,-0.2f);
			
			Minecraft.getMinecraft().getItemRenderer().renderItem(living,wings,null);
			GL11.glPopMatrix();

			GL11.glPushMatrix();

			Item[] LOCK= new Item[] {RiderItems.wdriverj,RiderItems.wdriverm,RiderItems.wdrivert,RiderItems.wdrivercc,RiderItems.wdriverx,RiderItems.wdriverx,RiderItems.wdriverxca};
			Item[] LOCK2= new Item[] {RiderItems.wdriverc,RiderItems.wdriverh,RiderItems.wdriverl,RiderItems.wdriverf,RiderItems.wdriverjj,RiderItems.wdriverx,RiderItems.wdriverx};

			Item[] LOCKa= new Item[] {ShowaRiderItems.blanknoitem,RiderItems.accel_drivert,RiderItems.accel_driverb};
			
			Item sidea= ShowaRiderItems.blanknoitem;
			Item sideb= ShowaRiderItems.blanknoitem;
			Item sideex= ShowaRiderItems.blanknoitem;
		
			if (stack.hasTagCompound()){
				if(stack.getItem() ==RiderItems.Wdriver){
					sidea= LOCK[stack.getTagCompound().getInteger("core1")];
					sideb= LOCK2[stack.getTagCompound().getInteger("core3")];
					if (stack.getTagCompound().getInteger("core2")>2){
						sidea=ShowaRiderItems.blanknoitem;
						sideb=ShowaRiderItems.blanknoitem;
						sideex= RiderItems.wdriverxca;
					}else if (stack.getTagCompound().getInteger("core2")>0){
						sidea=ShowaRiderItems.blanknoitem;
						sideb=ShowaRiderItems.blanknoitem;
						sideex= RiderItems.wdriverx;
					}
				}else if(stack.getItem() ==RiderItems.accel_driver){
					sidea= LOCKa[stack.getTagCompound().getInteger("core1")];
				}	
			}else {
				if(stack.getItem() ==RiderItems.Wdriver){
					sidea= LOCK[0];
					sideb= LOCK2[0];
				}else if(stack.getItem() ==RiderItems.accel_driver){
					sidea= LOCKa[0];
					sideb=ShowaRiderItems.blanknoitem;
				}	
			}
			
			if(living.isSneaking()){
				GL11.glRotatef(20, 1, 0, 0);	
			}

			double dri = 0; 
			GL11.glRotatef(180, 0, 1, 0);

			GL11.glRotatef(180, 0, 0, 1);
			//EntityItem entItem= new EntityItemFrame(player.worldObj);
			//RenderEntityItem.doRender(entItem,4,-0.9,0.17,0,0);
			// Minecraft.getMinecraft().getRenderItem().renderItemModel(stack);
			GL11.glScaled(0.6, 0.6,0.6);

			GL11.glTranslatef((float) (0f+dri),-1.1f,0.3f);
			
			Minecraft.getMinecraft().getItemRenderer().renderItem(living,belt,null);
			
			Minecraft.getMinecraft().getItemRenderer().renderItem(living, new ItemStack(sideex),null);
			Minecraft.getMinecraft().getItemRenderer().renderItem(living, new ItemStack(sidea),null);
			Minecraft.getMinecraft().getItemRenderer().renderItem(living, new ItemStack(sideb),null);
			
			GL11.glPopMatrix();
			GL11.glPopMatrix();
			
	}

}




private void setRotation(ModelRenderer model, float x, float y, float z)
{
	model.rotateAngleX = x;
	model.rotateAngleY = y;
	model.rotateAngleZ = z;
}




public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
{
	super.setRotationAngles( par1, par2, par3, par4, par5,par6, par7Entity);

}

}
