// Date: 12/31/2018 10:21:22 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Kamen_Rider_Craft_4TH.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFangMemory extends ModelBiped {
	// fields
	ModelRenderer Body;
	ModelRenderer Head;
	ModelRenderer Tail;
	ModelRenderer LowerHalf;
	ModelRenderer LeftLeg;
	ModelRenderer RightLeg;
	ModelRenderer Spike;
	ModelRenderer RightFoot;
	ModelRenderer LeftFoot;
	ModelRenderer Paw;
	ModelRenderer LowerLeg;

	public ModelFangMemory()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, -1F, 0F, 1, 1, 4);
      Body.setRotationPoint(-1F, 21F, -2.066667F);
      Body.setTextureSize(64, 64);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(-1F, 0F, -1.833333F, 1, 1, 2);
      Head.setRotationPoint(0F, 19F, -2F);
      Head.setTextureSize(64, 64);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Tail = new ModelRenderer(this, 0, 0);
      Tail.addBox(0F, 0F, 4F, 1, 1, 2);
      Tail.setRotationPoint(-1F, 20F, -2.533333F);
      Tail.setTextureSize(64, 64);
      Tail.mirror = true;
      setRotation(Tail, 0.0571199F, 0F, 0F);
      LowerHalf = new ModelRenderer(this, 0, 0);
      LowerHalf.addBox(0F, 0F, 0F, 1, 1, 4);
      LowerHalf.setRotationPoint(-1F, 20.66667F, -2F);
      LowerHalf.setTextureSize(64, 64);
      LowerHalf.mirror = true;
      setRotation(LowerHalf, -0.1142397F, 0F, 0F);
      LeftLeg = new ModelRenderer(this, 0, 0);
      LeftLeg.addBox(0F, 0F, 0F, 1, 2, 2);
      LeftLeg.setRotationPoint(-1.5F, 19.6F, -0.7F);
      LeftLeg.setTextureSize(64, 64);
      LeftLeg.mirror = true;
      setRotation(LeftLeg, 0F, 0F, 0F);
      RightLeg = new ModelRenderer(this, 0, 0);
      RightLeg.addBox(0F, 0F, 0F, 1, 2, 2);
      RightLeg.setRotationPoint(-0.5333334F, 19.6F, -0.7F);
      RightLeg.setTextureSize(64, 64);
      RightLeg.mirror = true;
      setRotation(RightLeg, 0F, 0F, 0F);
      Spike = new ModelRenderer(this, 0, 0);
      Spike.addBox(0F, 0F, 0F, 1, 1, 2);
      Spike.setRotationPoint(-1F, 19F, -4F);
      Spike.setTextureSize(64, 64);
      Spike.mirror = true;
      setRotation(Spike, 0.2572064F, 0F, 0F);
      RightFoot = new ModelRenderer(this, 0, 0);
      RightFoot.addBox(0F, 0F, 0F, 1, 1, 2);
      RightFoot.setRotationPoint(-0.5F, 23F, -0.5F);
      RightFoot.setTextureSize(64, 64);
      RightFoot.mirror = true;
      setRotation(RightFoot, 0F, 0F, 0F);
      LeftFoot = new ModelRenderer(this, 0, 0);
      LeftFoot.addBox(0F, 0F, 0F, 1, 1, 2);
      LeftFoot.setRotationPoint(-1.5F, 23F, -0.5F);
      LeftFoot.setTextureSize(64, 64);
      LeftFoot.mirror = true;
      setRotation(LeftFoot, 0F, 0F, 0F);
      Paw = new ModelRenderer(this, 0, 0);
      Paw.addBox(0F, 0F, 0F, 1, 1, 2);
      Paw.setRotationPoint(-1F, 21F, -3F);
      Paw.setTextureSize(64, 64);
      Paw.mirror = true;
      setRotation(Paw, 0F, 0F, 0F);
      LowerLeg = new ModelRenderer(this, 0, 0);
      LowerLeg.addBox(0F, 0F, 0F, 1, 1, 1);
      LowerLeg.setRotationPoint(-1F, 22F, 0.5F);
      LowerLeg.setTextureSize(64, 64);
      LowerLeg.mirror = true;
      setRotation(LowerLeg, 0F, 0F, 0F);
  }

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Body.render(f5);
		Head.render(f5);
		Tail.render(f5);
		LowerHalf.render(f5);
		LeftLeg.render(f5);
		RightLeg.render(f5);
		Spike.render(f5);
		RightFoot.render(f5);
		LeftFoot.render(f5);
		Paw.render(f5);
		LowerLeg.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
