// Date: 27/05/2015 23:35:12
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package Kamen_Rider_Craft_4TH.model;

import org.lwjgl.opengl.GL11;

import Kamen_Rider_Craft_4TH.RiderItems;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.entity.RenderManager;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.item.EntityItem;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Items;
import net.minecraft.inventory.EntityEquipmentSlot;
import net.minecraft.item.EnumAction;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class model_belt extends ModelBiped
{
	//fields
	

	public ItemStack belt;




	public model_belt()
	{
		textureWidth = 64;
		textureHeight = 128;


	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		if (entity instanceof EntityLivingBase){
			EntityLivingBase living = ((EntityLivingBase)entity);
			
			GL11.glPushMatrix();

			ItemStack stack = living.getItemStackFromSlot(EntityEquipmentSlot.FEET);
			Item Belt = belt.getItem();
			
			EntityItem entItem = new EntityItem(Minecraft.getMinecraft().player.getEntityWorld(), 0D, 0D, 0D,living.getItemStackFromSlot(EntityEquipmentSlot.FEET));
			//Without the below line, the item will spazz out
			entItem.hoverStart = 1.0F;

			if(living.isSneaking()){
				GL11.glRotatef(20, 1, 0, 0);	
			}

			double dri = 0; 
			GL11.glRotatef(180, 0, 1, 0);

			GL11.glRotatef(180, 0, 0, 1);
			GL11.glScaled(0.35, 0.35,0.35);

			GL11.glTranslatef((float) (0f+dri),-2f,0.6f);


			Minecraft.getMinecraft().getItemRenderer().renderItem(living,belt,null);
			
		
		

			GL11.glPopMatrix();
			
	}

}




private void setRotation(ModelRenderer model, float x, float y, float z)
{
	model.rotateAngleX = x;
	model.rotateAngleY = y;
	model.rotateAngleZ = z;
}




public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
{
	super.setRotationAngles( par1, par2, par3, par4, par5,par6, par7Entity);

}

}
