// Date: 24/08/2013 15:36:02
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package KamenRiderCraftV3.model;

import org.lwjgl.opengl.GL11;


import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class Biped extends ModelBiped
{
	public ModelRenderer bipedBody2;

  public Biped()
  {
	  this.bipedBody2 = new ModelRenderer(this, 16, 16);
      this.bipedBody2.addBox(-4.0F, 0.0F, -2.0F, 8, 12, 4, 1);
      this.bipedBody2.setRotationPoint(0.0F, 0.0F , 0.0F);
      
       

  }
  @Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
	 // super.render(entity,f,f1,f2, f3, f4, f5);
	    

		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		
		GL11.glPushMatrix();
	
		
		GL11.glPushMatrix();
        GL11.glScalef(1.2F, 1.2F, 1.2F);
        if(entity.isSneaking()){
        	GL11.glTranslatef(0, 0.17F, -0.02f);
        }else{
	       GL11.glTranslatef(0, -0F, 0);
        }
       this.bipedHead.render(f5);
       this.bipedHeadwear.render(f5);
        
        
        GL11.glPopMatrix();
        
        GL11.glScalef(1.05F, 1.05F, 1.05F);
        if(entity.isSneaking()){
        	GL11.glTranslatef(0, 0.2F, 0);
        }else{
	       GL11.glTranslatef(0, -0.02F, 0);
        }
	        this.bipedBody2.render(f5);
	        
	        GL11.glPopMatrix();
        
	}
  
  /**
   * Sets the model's various rotation angles. For bipeds, par1 and par2 are used for animating the movement of arms
   * and legs, where par1 represents the time(so that arms and legs swing back and forth) and par2 represents how
   * "far" arms and legs can swing at most.
   */
  public void setRotationAngles(float p_78087_1_, float p_78087_2_, float p_78087_3_, float p_78087_4_, float p_78087_5_, float p_78087_6_, Entity entityIn)
  {
	  super.setRotationAngles( p_78087_1_, p_78087_2_, p_78087_3_, p_78087_4_, p_78087_5_,p_78087_5_, entityIn);
     copyModelAngles(this.bipedBody, this.bipedBody2);
  }


	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}



	
	
}

