// Date: 24/08/2013 15:36:02
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package KamenRiderCraftV3.model;

import org.lwjgl.opengl.GL11;

import KamenRiderCraftV3.RiderItems;
import KamenRiderCraftV3.item.Ex_Aid.item_ex_aiddriver;
import KamenRiderCraftV3.item.fourze.item_Fourzedriver;
import KamenRiderCraftV3.item.gaim.item_Gaimdriver;
import KamenRiderCraftV3.item.ghost.item_ghostdriver;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.EnumAction;
import net.minecraft.item.ItemStack;
import net.minecraft.util.MathHelper;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;


public class Bipedswich extends ModelBiped
{
	/** The Biped's Right Arm */
	public ModelRenderer bipedRightArm2;
	/** The Biped's Left Arm */
	public ModelRenderer bipedLeftArm2;
	/** The Biped's Right Leg */
	public ModelRenderer bipedRightLeg2;
	/** The Biped's Left Leg */
	public ModelRenderer bipedLeftLeg2;

	public Bipedswich()
	{
		this.bipedRightArm2 = new ModelRenderer(this, 40, 16);
		this.bipedRightArm2.addBox(-3.0F, -2.0F, -2.0F, 4, 12, 4, 1);
		this.bipedRightArm2.setRotationPoint(-5.0F, 2.0F , 0.0F);
		this.bipedLeftArm2= new ModelRenderer(this, 40, 16);
		this.bipedLeftArm2.mirror = true;
		this.bipedLeftArm2.addBox(-1.0F, -2.0F, -2.0F, 4, 12, 4, 1);
		this.bipedLeftArm2.setRotationPoint(5.0F, 2.0F , 0.0F);
		this.bipedRightLeg2 = new ModelRenderer(this, 0, 16);
		this.bipedRightLeg2.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 1);
		this.bipedRightLeg2.setRotationPoint(-1.9F, 12.0F , 0.0F);
		this.bipedLeftLeg2 = new ModelRenderer(this, 0, 16);
		this.bipedLeftLeg2.mirror = true;
		this.bipedLeftLeg2.addBox(-2.0F, 0.0F, -2.0F, 4, 12, 4, 1);
		this.bipedLeftLeg2.setRotationPoint(1.9F, 12.0F , 0.0F);
	}



	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		if (entity instanceof  EntityPlayer){
			if (((EntityPlayer) entity).getCurrentEquippedItem()!= null){
				if (((EntityPlayer) entity).getCurrentEquippedItem().getItemUseAction() == EnumAction.BLOCK){
					if (((EntityPlayer) entity).isUsingItem()){
						heldItemRight = 3;
					}
					aimedBow = false;
				}else
					if (((EntityPlayer) entity).getCurrentEquippedItem().getItemUseAction() == EnumAction.BOW){

						aimedBow = ((EntityPlayer) entity).isUsingItem();
					}else {


						aimedBow = false;

					}
			}
		}
		this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		
		GL11.glPushMatrix();
		GL11.glScalef(1.1F, 1.1F, 1.1F);



		if (entity.isSneaking()){
			GL11.glTranslatef(0, 0.2F, 0);

		}else {
			GL11.glTranslatef(0, -0.02F, 0);


		}
		this.bipedRightArm2.offsetX=-0.02f;
		if (entity instanceof  EntityLivingBase){
			ItemStack stack  =   ((EntityLivingBase) entity).getEquipmentInSlot(1);

				Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("KamenRiderCraftv3:textures/armor/"+item_Fourzedriver.get_CircleModule(stack)+".png"));	
		}
		this.bipedRightArm2.render(f5);
		GL11.glPopMatrix();
		

		GL11.glPushMatrix();
		GL11.glScalef(1F, 1F, 1F);


		if (entity.isSneaking()){
			GL11.glTranslatef(0, 0.3F, 0);

		}else {
			GL11.glTranslatef(0, 0.02F, 0);


		}


		this.bipedRightLeg2.offsetX=-0.045f;
		if (entity instanceof  EntityLivingBase){
			ItemStack stack  =   ((EntityLivingBase) entity).getEquipmentInSlot(1);

				Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("KamenRiderCraftv3:textures/armor/"+item_Fourzedriver.get_CrossModule(stack)+".png"));	
		}
		this.bipedRightLeg2.render(f5);



		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glScalef(1.1F, 1.1F, 1.1F);



		if (entity.isSneaking()){
			GL11.glTranslatef(0, 0.2F, 0);

		}else {
			GL11.glTranslatef(0, -0.02F, 0);


		}

		if (entity instanceof  EntityLivingBase){
			ItemStack stack  =   ((EntityLivingBase) entity).getEquipmentInSlot(1);

			if (stack!=null){
				

				Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("KamenRiderCraftv3:textures/armor/"+item_Fourzedriver.get_SquareModule(stack)+".png"));	
				
					
				
			}
		}
		this.bipedLeftArm2.offsetX=0.02f;
		this.bipedLeftArm2.render(f5);



		GL11.glPopMatrix();
		GL11.glPushMatrix();
		GL11.glScalef(1F, 1F, 1F);


		if (entity.isSneaking()){
			GL11.glTranslatef(0, 0.3F, 0);

		}else {
			GL11.glTranslatef(0, 0.02F, 0);


		}

		this.bipedLeftLeg2.offsetX=0.045f;

		if (entity instanceof  EntityLivingBase){
			ItemStack stack  =   ((EntityLivingBase) entity).getEquipmentInSlot(1);

			if (stack!=null){
						Minecraft.getMinecraft().renderEngine.bindTexture(new ResourceLocation("KamenRiderCraftv3:textures/armor/"+item_Fourzedriver.get_TriangleModule(stack)+".png"));	
				
			}
		}
		this.bipedLeftLeg2.render(f5);
		GL11.glPopMatrix();

	}

	public void setRotationAngles(float p_78087_1_, float p_78087_2_, float p_78087_3_, float p_78087_4_, float p_78087_5_, float p_78087_6_, Entity p_78087_7_)
	{
		super.setRotationAngles(p_78087_1_, p_78087_2_, p_78087_3_, p_78087_4_, p_78087_5_, p_78087_6_, p_78087_7_);
	
		copyModelAngles(this.bipedLeftArm, this.bipedLeftArm2);
		copyModelAngles(this.bipedLeftLeg, this.bipedLeftLeg2);
		copyModelAngles(this.bipedRightArm, this.bipedRightArm2);
		copyModelAngles(this.bipedRightLeg, this.bipedRightLeg2);

	}



}














